### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Grindyvin** [KCreator/Earth-Defence-Force-Documentation#3]
I do the first step, zipping and unzip it on the EDF 4.1 file (with the exe on it) but when i run it. I got the message "the application was unable to start correctly" 
And in the modloader's note it says "failed to determined what exe is running" so how to fix it? I want to use mods on the game

**Comment by KCreator** [comment]
It might be worth opening this issue on the modloader project's repo, found here: https://github.com/BlueAmulet/EDFModLoader

Inherently, this repo is to host a wiki containing various documentation about the game's engine, file formats and modification in general, so I will need to close this issue, as it is technically a bug report/request for assistance for a separate project.
